version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arka_db
    container_name: arka
    volumes:
      - ./postgres:/var/lib/postgresql/data
